services:
  - type: cron
    name: telegram-channel-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    schedule: "*/10 * * * *"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GIST_ID
        sync: false
      - key: SOURCE_CHANNEL
        value: o2tvseries_new
      - key: DEST_CHANNEL
        value: NewmovieandSeries0